# Generated by Django 5.0.8 on 2024-10-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0064_remove_conversation_temp_id_alter_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="texttoimagemodelconfig",
            name="api_base_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
