# Generated by Django 5.0.8 on 2024-10-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0065_texttoimagemodelconfig_api_base_url"),
        ("database", "0067_alter_agent_style_icon"),
    ]

    operations = []
